services:
  - type: web
    name: web
    region: ohio
    env: python
    plan: free

    buildCommand: |
      npm ci
      npm run build
      pipenv install --deploy --ignore-pipfile

    startCommand: |
      # Run migrations against Render’s DATABASE_URL
      pipenv run flask db upgrade

      # Bind Gunicorn to Render’s port env var
      pipenv run gunicorn wsgi:application \
        --bind 0.0.0.0:${PORT} \
        --chdir src

    envVars:
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USE_TLS
        value: "False"
      - key: MAIL_USERNAME
        value: dshustin@gmail.com
      - key: MAIL_PASSWORD
        value: <YOUR-GMAIL-APP-PASSWORD>
      - key: MAIL_DEFAULT_SENDER
        value: dshustin@gmail.com

databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    plan: free