services:
  - type: web
    name: web
    region: ohio
    env: python
    plan: free

    # BUILD PHASE (no DB connection)
    buildCommand: |
      npm ci
      npm run build
      pipenv install --deploy --ignore-pipfile

    # START PHASE (DB is available via DATABASE_URL)
    startCommand: |
      pipenv run flask db upgrade
      pipenv run gunicorn wsgi --chdir src

    envVars:
      - key: PYTHON_VERSION
        value: "3.10.6"
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "465"
      - key: MAIL_USE_TLS
        value: "False"
      - key: MAIL_USERNAME
        value: dshustin@gmail.com
      - key: MAIL_PASSWORD
        value: <YOUR-GMAIL-APP-PASSWORD>
      - key: MAIL_DEFAULT_SENDER
        value: dshustin@gmail.com

# 2) Your Postgres database under `databases:`
databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    plan: free