import React from "react";


export const About = () => {
    return (

        <div>
            
            <div className="page-content">
                <h1>About</h1>
                <p>This is the About page.</p>
                {/* <div>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum arcu nec risus tincidunt, et accumsan mi bibendum. Cras id feugiat magna. Phasellus vitae viverra lacus. Pellentesque lacinia congue metus, a dapibus tortor. Fusce ac dignissim turpis, nec vestibulum justo. Sed vitae lorem vitae enim euismod tristique. Sed finibus nisl eget purus volutpat, in dapibus erat tincidunt. Vivamus vehicula, sapien sed tincidunt blandit, eros nunc tempor mauris, non mollis purus tortor non magna.
                    Vestibulum sed tincidunt ligula, at faucibus mi. Duis congue vehicula velit, et placerat turpis. Vestibulum in vestibulum risus. Proin nec purus quam. Pellentesque posuere, tortor nec varius finibus, felis turpis dapibus lectus, id dapibus est justo ac sem. Aliquam viverra nisl sed nisi efficitur, in luctus erat porttitor. Proin dapibus ligula eget nulla lobortis, nec porttitor odio aliquam. Aenean a odio magna. Sed fringilla orci nulla, at tempor nisi dictum a.
                    Cras malesuada turpis id dignissim facilisis. Vestibulum tincidunt orci id lectus porttitor feugiat. Suspendisse tristique turpis at nisl bibendum, sed ultrices odio vehicula. Cras sodales ut ligula non vehicula. Mauris viverra quam at imperdiet euismod. In ac dolor a lorem ornare lobortis. Curabitur eget velit odio. Fusce dapibus, nisl nec scelerisque malesuada, augue arcu dapibus sem, vitae viverra nulla orci nec lacus. Sed lobortis tempor libero sed porttitor. Sed vitae augue a turpis varius feugiat. Curabitur nec odio velit. Curabitur imperdiet nulla nisi, in fermentum ex efficitur vitae.
                    Integer eu feugiat lacus. Phasellus sed lectus non justo pretium congue nec nec sapien. Nunc at velit a arcu ultrices hendrerit. Morbi vitae ante vitae sem porttitor lacinia. Pellentesque eu massa gravida, vulputate nisi id, placerat sapien. Curabitur porttitor eros sit amet orci dignissim, a tristique sem malesuada. Integer eget nulla et erat volutpat scelerisque nec vel turpis. Nunc commodo, tortor nec convallis tristique, lacus nisl scelerisque nunc, vel pulvinar felis turpis vitae leo.
                    Vivamus tincidunt bibendum justo, at congue erat tempor at. Sed lobortis posuere arcu at commodo. Maecenas eget turpis malesuada, faucibus arcu at, condimentum neque. Suspendisse potenti. Integer vestibulum ligula sapien, in tempor nisi sagittis at. Donec euismod felis nec dolor fringilla, eget pretium elit ornare. Pellentesque eu tortor tempor, faucibus risus sed, suscipit magna. Nullam vulputate, lacus nec dignissim rhoncus, nulla libero malesuada elit, id bibendum dolor turpis vel velit.
                    Morbi in nibh nec odio accumsan varius. Vestibulum varius fermentum magna, in sagittis est posuere vitae. Curabitur sed magna in arcu bibendum facilisis. Fusce mattis quam sit amet felis lacinia convallis. In posuere, felis et tincidunt fringilla, sem sapien congue orci, a efficitur erat odio non leo. Integer dictum ac lorem id sagittis. Proin nec faucibus lectus. Nulla ac purus elit. Sed consequat turpis lorem, nec varius augue bibendum non.
                </div>
                <div>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum arcu nec risus tincidunt, et accumsan mi bibendum. Cras id feugiat magna. Phasellus vitae viverra lacus. Pellentesque lacinia congue metus, a dapibus tortor. Fusce ac dignissim turpis, nec vestibulum justo. Sed vitae lorem vitae enim euismod tristique. Sed finibus nisl eget purus volutpat, in dapibus erat tincidunt. Vivamus vehicula, sapien sed tincidunt blandit, eros nunc tempor mauris, non mollis purus tortor non magna.
                    Vestibulum sed tincidunt ligula, at faucibus mi. Duis congue vehicula velit, et placerat turpis. Vestibulum in vestibulum risus. Proin nec purus quam. Pellentesque posuere, tortor nec varius finibus, felis turpis dapibus lectus, id dapibus est justo ac sem. Aliquam viverra nisl sed nisi efficitur, in luctus erat porttitor. Proin dapibus ligula eget nulla lobortis, nec porttitor odio aliquam. Aenean a odio magna. Sed fringilla orci nulla, at tempor nisi dictum a.
                    Cras malesuada turpis id dignissim facilisis. Vestibulum tincidunt orci id lectus porttitor feugiat. Suspendisse tristique turpis at nisl bibendum, sed ultrices odio vehicula. Cras sodales ut ligula non vehicula. Mauris viverra quam at imperdiet euismod. In ac dolor a lorem ornare lobortis. Curabitur eget velit odio. Fusce dapibus, nisl nec scelerisque malesuada, augue arcu dapibus sem, vitae viverra nulla orci nec lacus. Sed lobortis tempor libero sed porttitor. Sed vitae augue a turpis varius feugiat. Curabitur nec odio velit. Curabitur imperdiet nulla nisi, in fermentum ex efficitur vitae.
                    Integer eu feugiat lacus. Phasellus sed lectus non justo pretium congue nec nec sapien. Nunc at velit a arcu ultrices hendrerit. Morbi vitae ante vitae sem porttitor lacinia. Pellentesque eu massa gravida, vulputate nisi id, placerat sapien. Curabitur porttitor eros sit amet orci dignissim, a tristique sem malesuada. Integer eget nulla et erat volutpat scelerisque nec vel turpis. Nunc commodo, tortor nec convallis tristique, lacus nisl scelerisque nunc, vel pulvinar felis turpis vitae leo.
                    Vivamus tincidunt bibendum justo, at congue erat tempor at. Sed lobortis posuere arcu at commodo. Maecenas eget turpis malesuada, faucibus arcu at, condimentum neque. Suspendisse potenti. Integer vestibulum ligula sapien, in tempor nisi sagittis at. Donec euismod felis nec dolor fringilla, eget pretium elit ornare. Pellentesque eu tortor tempor, faucibus risus sed, suscipit magna. Nullam vulputate, lacus nec dignissim rhoncus, nulla libero malesuada elit, id bibendum dolor turpis vel velit.
                    Morbi in nibh nec odio accumsan varius. Vestibulum varius fermentum magna, in sagittis est posuere vitae. Curabitur sed magna in arcu bibendum facilisis. Fusce mattis quam sit amet felis lacinia convallis. In posuere, felis et tincidunt fringilla, sem sapien congue orci, a efficitur erat odio non leo. Integer dictum ac lorem id sagittis. Proin nec faucibus lectus. Nulla ac purus elit. Sed consequat turpis lorem, nec varius augue bibendum non.
                </div>
                <div>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam dictum arcu nec risus tincidunt, et accumsan mi bibendum. Cras id feugiat magna. Phasellus vitae viverra lacus. Pellentesque lacinia congue metus, a dapibus tortor. Fusce ac dignissim turpis, nec vestibulum justo. Sed vitae lorem vitae enim euismod tristique. Sed finibus nisl eget purus volutpat, in dapibus erat tincidunt. Vivamus vehicula, sapien sed tincidunt blandit, eros nunc tempor mauris, non mollis purus tortor non magna.
                    Vestibulum sed tincidunt ligula, at faucibus mi. Duis congue vehicula velit, et placerat turpis. Vestibulum in vestibulum risus. Proin nec purus quam. Pellentesque posuere, tortor nec varius finibus, felis turpis dapibus lectus, id dapibus est justo ac sem. Aliquam viverra nisl sed nisi efficitur, in luctus erat porttitor. Proin dapibus ligula eget nulla lobortis, nec porttitor odio aliquam. Aenean a odio magna. Sed fringilla orci nulla, at tempor nisi dictum a.
                    Cras malesuada turpis id dignissim facilisis. Vestibulum tincidunt orci id lectus porttitor feugiat. Suspendisse tristique turpis at nisl bibendum, sed ultrices odio vehicula. Cras sodales ut ligula non vehicula. Mauris viverra quam at imperdiet euismod. In ac dolor a lorem ornare lobortis. Curabitur eget velit odio. Fusce dapibus, nisl nec scelerisque malesuada, augue arcu dapibus sem, vitae viverra nulla orci nec lacus. Sed lobortis tempor libero sed porttitor. Sed vitae augue a turpis varius feugiat. Curabitur nec odio velit. Curabitur imperdiet nulla nisi, in fermentum ex efficitur vitae.
                    Integer eu feugiat lacus. Phasellus sed lectus non justo pretium congue nec nec sapien. Nunc at velit a arcu ultrices hendrerit. Morbi vitae ante vitae sem porttitor lacinia. Pellentesque eu massa gravida, vulputate nisi id, placerat sapien. Curabitur porttitor eros sit amet orci dignissim, a tristique sem malesuada. Integer eget nulla et erat volutpat scelerisque nec vel turpis. Nunc commodo, tortor nec convallis tristique, lacus nisl scelerisque nunc, vel pulvinar felis turpis vitae leo.
                    Vivamus tincidunt bibendum justo, at congue erat tempor at. Sed lobortis posuere arcu at commodo. Maecenas eget turpis malesuada, faucibus arcu at, condimentum neque. Suspendisse potenti. Integer vestibulum ligula sapien, in tempor nisi sagittis at. Donec euismod felis nec dolor fringilla, eget pretium elit ornare. Pellentesque eu tortor tempor, faucibus risus sed, suscipit magna. Nullam vulputate, lacus nec dignissim rhoncus, nulla libero malesuada elit, id bibendum dolor turpis vel velit.
                    Morbi in nibh nec odio accumsan varius. Vestibulum varius fermentum magna, in sagittis est posuere vitae. Curabitur sed magna in arcu bibendum facilisis. Fusce mattis quam sit amet felis lacinia convallis. In posuere, felis et tincidunt fringilla, sem sapien congue orci, a efficitur erat odio non leo. Integer dictum ac lorem id sagittis. Proin nec faucibus lectus. Nulla ac purus elit. Sed consequat turpis lorem, nec varius augue bibendum non.
                </div> */}
            </div>
        </div>
    );
};